In [8]:
import pandas as pd
import numpy as np

In [6]:
df = pd.read_csv('C:/Documents/Projects_IC/creativision_nyu/UrbanCreativision/video_folder/instance_0_/instance_data.csv')
df.head()

Unnamed: 0                                         frame_path  \
0           0  UrbanCreativision/video_folder\instance_0_\fra...   
1           1  UrbanCreativision/video_folder\instance_0_\fra...   
2           2  UrbanCreativision/video_folder\instance_0_\fra...   
3           3  UrbanCreativision/video_folder\instance_0_\fra...   
4           4  UrbanCreativision/video_folder\instance_0_\fra...   

                                           moondream  \
0  \nThe scene features a bus stop with three ben...   
1  \nThe scene features a yellow and black car dr...   
2  \nThe scene features a bus stop with two buses...   
3  \nThe scene features a bus stop with several p...   
4  \nThe scene features a bus stop with several b...   

                                        llava-llama3  
0  The image captures a serene scene on a street ...  
1  The image captures a vibrant scene on a bustli...  
2  The image captures a serene scene at dusk. Dom...  
3  The image captures a tranquil scene on a city ...  
4  The image captures a vibrant street scene. Dom...

In [12]:
evec = np.load(
'C:/Documents/Projects_IC/creativision_nyu/UrbanCreativision/video_folder/instance_0_/desc_evecs/moondream/mxbai-embed-large.npy',
allow_pickle=True)
print(f'length {len(evec)}')
print(f'[0] test: {evec[0]} \n of length: {len(evec[0][0])}')
print(f'[1] test: {evec[0]} \n of length: {len(evec[1][0])}')
print(f'[2] test: {evec[0]} \n of length: {len(evec[2][0])}')
print(evec)


length 5
[0] test: [[-0.0317531  -0.02199691  0.02541651 ...  0.02937894  0.02444509
  -0.01554112]] 
 of length: 1024
[1] test: [[-0.0317531  -0.02199691  0.02541651 ...  0.02937894  0.02444509
  -0.01554112]] 
 of length: 1024
[2] test: [[-0.0317531  -0.02199691  0.02541651 ...  0.02937894  0.02444509
  -0.01554112]] 
 of length: 1024
[array([[-0.0317531 , -0.02199691,  0.02541651, ...,  0.02937894,
          0.02444509, -0.01554112]])
 array([[-0.03009281,  0.01448206,  0.00948387, ...,  0.01632137,
          0.00996914, -0.00114731]])
 array([[-0.03366906, -0.00272325,  0.03606004, ...,  0.02676331,
          0.01237146, -0.02548826]])
 array([[-0.02763887,  0.00159152,  0.02461776, ...,  0.00527816,
          0.0104032 , -0.01711758]])
 array([[-0.00922564, -0.01612805,  0.0271265 , ...,  0.02891844,
          0.00733939, -0.00534367]])                             ]
